spring:
 profiles:
   active:
   - dev
---
spring:
 profiles: dev   #开发环境
 application:
  name: spring-cloud-config-xiongwei-dev
---
spring:
 profiles: test  #测试环境
 application: spring-cloud-config-xiongwei-test
# 请保存为UTF-8格式